# -*- coding: utf-8 -*-
"""DigitRecognitionUsingRandomForest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LZ_8lyMrqgTDc3ha1y88chLUFzi06Wcp

import libraries
"""

import pandas as pd
import numpy as np

"""Access google drive  contents"""

from google.colab import drive
drive.mount('/content/gdrive')

"""Load dataset"""

filename = '/content/gdrive/My Drive/digit.csv'
dataset = pd.read_csv(filename)

"""Summarize dataset"""

print(dataset.shape)
print(dataset.head(5))

"""Segregate Dataset into x(input) and y(output)"""

x = dataset.iloc[:, 1:]
print(x)
print(x.shape)

y = dataset.iloc[: , 0]
print(y)
print(y.shape)

"""Split dataset into text and train"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

"""Training"""

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 350 , criterion = "gini", max_depth = 50)
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

"""Accuracy"""

from sklearn.metrics import accuracy_score
print("Accuracy of the model: {0}%",format(accuracy_score(y_test, y_pred)*100))

import matplotlib.pyplot as plt
index = 10
print("predicted:" + str(model.predict(x_test)[index]))
plt.axis('off')
plt.imshow(x_test.iloc[index].values.reshape((28,28)), cmap='gray')

